name: Run Tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run test:github
      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: ./coverage/lcov.info
