name: Upload test coverage to Coveralls

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Download coverage report artifact"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.event.workflow_run.id }},
            });
            var testCoverage = artifacts.data.artifacts.find(
              (artifact) => artifact.name == "test-coverage"
            );
            var coverallsFolder = artifacts.data.artifacts.find(
              (artifact) => artifact.name == "coveralls_folder"
            )
            var artifact = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              archive_format: 'zip',
            }
            var testCoverageZip = await github.actions.downloadArtifact({
              ...artifact,
              artifact_id: testCoverage.id
            });
            var coverallsFolderZip = await github.actions.downloadArtifact({
              ...artifact,
              artifact_id: coverallsFolder.id
            })
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/test-coverage.zip', Buffer.from(testCoverageZip.data));
            fs.writeFileSync('${{github.workspace}}/coveralls_folder.zip', Buffer.from(coverallsFolderZip.data));
      - run: unzip test-coverage.zip
      - run: unzip ./coveralls_folder.zip
      - run: cat lcov.info | ./coveralls/bin/coveralls.js
