name: Upload test coverage to Coveralls

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.workflow_run.event == 'push' &&
        github.event.workflow_run.conclusion == 'success'
      }}
    steps:
      - name: "Download coverage report artifact"
        uses: actions/download-artifact@v2
        with:
          name: test-coverage
          path: ./coverage

      - name: "Show that file was downloaded"
        run: ll
        working-directory: ./coverage
